sudo: required
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email: false

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-travis || echo "cargo-travis already installed"

script:
  - cargo build
  - QUICKCHECK_TESTS=5000 cargo test
  - cargo bench

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo coveralls
  fi

notifications:
  email: false
  slack: imdea-software:fdyPmym7oicfvSQTL5zy21n3
