sudo: required
language: rust
rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email: false

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      # <tarpaulin>
      # - libssl-dev
      # </tarpaulin>

      # <travis>
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - cmake
    sources:
      - kalakris-cmake
      # </travis>

before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    export PATH=$HOME/.cargo/bin:$PATH

    # <tarpaulin>
    # cargo install cargo-tarpaulin || echo "cargo-tarpaulin already installed"
    # </tarpaulin>

    # <travis>
    cargo install cargo-travis || echo "cargo-travis already installed"
    # </travis>

  fi

script:
  - cargo build
  - cargo test

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    # measure code coverage and upload to coveralls.io

    # <tarpaulin>
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    # </tarpaulin>

    # <travis>
    cargo coveralls
    # </travis>

  fi

notifications:
  email: false
  slack: imdea-software:fdyPmym7oicfvSQTL5zy21n3
