sudo: required
language: rust
rust:
  - nightly

matrix:
  include:
    - os: linux
      rust: nightly
  fast_finish: true

notifications:
  email: false

cache:
  cargo: true
  apt: true

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

script:
  - export CARGO_INCREMENTAL=0
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
  - export RUSTDOCFLAGS="-Cpanic=abort"
  - cargo build
  - QUICKCHECK_TESTS=10000 cargo test 
  # measure code coverage and upload to coveralls.io
  - grcov ./target/debug -t coveralls --llvm --branch --ignore-not-existing --service-name travis-ci --service-job-id $TRAVIS_JOB_ID -s . > coveralls.json

notifications:
  email: false
  slack: imdea-software:fdyPmym7oicfvSQTL5zy21n3
